version: '3.7'
services:
  apiservice: &apiservice
    image: apiservice
    #command: sh -c "sleep 10 && echo "* * * * * root npm run db:reset && npm run seed >> /var/log/cron.log 2>&1" > /etc/cron.d/resetdb-cron && chmod 0644 /etc/cron.d/resetdb-cron"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pgsqldbservice
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}

  pgsqldbservice:
    image: postgres:16-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_EXIT_DB_PORT}:${POSTGRES_DB_PORT}'
